before_install:
- sudo apt-get update 
- sudo apt-get install texlive-latex-extra
- sudo apt-get install texlive-science

script:
- mkdir _build
- cd ./tex
- pdflatex -output-directory ../_build ./Exercise01.tex
- pdflatex -output-directory ../_build ./Exercise01.tex
- pdflatex -output-directory ../_build ./Exercise01_solutions.tex
- pdflatex -output-directory ../_build ./Exercise01_solutions.tex
- pdflatex -output-directory ../_build ./Exercise02.tex
- pdflatex -output-directory ../_build ./Exercise02.tex
- pdflatex -output-directory ../_build ./Exercise02_solutions.tex
- pdflatex -output-directory ../_build ./Exercise02_solutions.tex
- cd ..

deploy:
  provider: releases
  api_key:
   secure: "x9++pZyKhPNHp414NrDQiMfDKJDTPFIJgWXwXkRieGlUNJxn1iejcHkNqM9Vd4f4NL+ld7keqwYyEf6uoDO/7+Oq8CxDVK6UeYuFFcf/489MrwmfESatcgKEAnJgA7tywh48OuGGKF0pjpltYlbRi6dzca2bvwce4zZ/GB4ORmgmmYyPCzvvBvLvZei3RexCcGdslSmoLApvVbAASwyZ2oEA3qApMaYFC6smGEzjOKXwsOLdw2QjcHF0g7sxEshZpgHLKeBxql9cQWcVqReM/UlkSbDqD/TPoqMZQlZ5UH0Z4RzNJPhMB8VpsbJh7GYfInT6/v+FV1HG0b1TqNyjMjBs0sMTEw1MKIx6rbxri4RgV/QG9lXNjrCd33ult1mJAHzuEmFGJ6lvYO3S67po3RKPyO70g4qMCPiez15ndIGQItmqvXyQX77UFInTaloaSbmZ5nWt1ehS91Tj6RosLhDC2cbBKdZis34sH3zwR1Y1rInTr/ViKd0/m+/wjnd2dXTaL3qtTu1+6k3liHdnsyDYEw4NKKS+H7Qnc7HeP8RyMfNotIlNxhcOwCCTL4tF3vhpCEmABfTbEeRQZ5aK7MozQLWa54yqvGT3HUEW4uA90X+0EQiBoRcWqGSERzkk3b4RE+0MQSnB9knE5+l6z2EJOsit2VkD1kGvMpSdzpg="
  file: ./_build/*.pdf
  file_glob: true
  skip_cleanup: true
  on:
    repo: takayasaito/INF281-Exercises
    tags: true
